openapi: 3.1.0
info:
  title: Fit Acts
  version: 1.0.0
components:
  schemas:
    users:
      type: object
      properties:
        user_id:
          type: integer
          format: int
          example: 1
        name:
          type: string
          format: varChar
          example: "John Doe"
        email:
          type: string
          format: varChar
          example: "john@gmail.com"
          uniqueItems: true 
        password:
          type: string
          format: varChar
          example: "$2b$10$wDuSt/SVxQqdZ67GqRYubepcDaVMS3HbRxi9/3k4UT09SRY3YXsxC"
        mobilenumber:
          type: integer
          format: bigint
          example: 1234567890
          uniqueItems: true 
        height:
          type: integer
          format: int
          example: 180
        weight:
          type: integer
          format: int
          example: 80
        aadhar:
          type: string
          format: varChar
          example: "aadhar.pdf"
        timeline:
          type: array
          items:
            type: integer
            format: int
          example: [1,2,3]
        favactivities:
          type: array
          items:
            type: integer
            format: int
          example: [1,2,3]
        following:
          type: array
          items:
            type: integer
            format: int
          example: [1,2,3]

      example: 
        user_id: 1
        name: "John Doe"
        email: "john@gmail.com"
        mobilenumber: 1234567890
        height: 180
        weight: 80
        aadhar: "aadhar.pdf"
        timeline: [1,2,3]
        favactivities: [1,2,3]
        following: [1,2,3]

    activities:
      type: object
      properties:
        activity_id:
          type: integer
          format: int
          example: 1
        activityName:
          type: string
          format: varChar
          example: "Running"
        calories:
          type: integer
          format: int
          example: 100
        benifitFor:
          type: array
          items:
            type: string
            format: varChar
          example: ["Heart","Lungs"]
        image:
          type: string
          format: varChar
          example: "https://apollohealthlib.blob.core.windows.net/health-library/2021/04/shutterstock_788590396-scaled.jpg"
        mts:
          type: boolean
          example: "true"

      example:
        activity_id: 1
        activityName: "Running"
        calories: 100
        benifitFor: ["Heart","Lungs"]
        image: "https://apollohealthlib.blob.core.windows.net/health-library/2021/04/shutterstock_788590396-scaled.jpg"
        mts: "true"
      
    performances:
      type: object
      properties:
        performance_id:
          type: integer
          format: int
          example: 1
        performancename:
          type: string
          format: varChar
          example: "John 1"
        duration:
          type: integer
          format: int
          example: 10
        distance:
          type: integer
          format: int
          example: 100
        speed:
          type: numeric
          format: float
          example: 10.0
        mts:
          type: boolean
          example: "true"
        user_id:
          type: integer
          format: int
          example: 1
        activity_id:
          type: integer
          format: int
          example: 1
        created_at:
          type: timestamp without time zone
          format: timestamp
          example: 2023-11-11 10:14:14.948

      example:
        performance_id: 1
        performancename: "John 1"
        duration: 10
        distance: 100
        speed: 10.0
        mts: "true"
        user_id: 1
        activity_id: 1
        created_at: 2023-11-11 10:14:14.948